[package]
name = "cargo-lichking"
version = "0.6.0"
authors = ["Wim Looman <wim@nemo157.com>"]

description = "Display info about licensing of dependencies"

repository = "https://github.com/Nemo157/cargo-lichking"

readme = "README.md"
keywords = ["cargo", "licensing"]

license = "MIT/Apache-2.0"

[dependencies]
cargo = "0.30"
clap = "2.20"
regex = "0.2"
void = "1.0"
